name: Continious Integration

on:
  push:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up mongo
        run: |
          docker run --rm -d -p 27017:27017 mongo:latest

      - name: Set up imgproxy
        working-directory: imgproxy
        run: |
          docker run --rm -d --env-file env.list -v $(pwd)/data:/data:ro -v $(pwd)/filesystem:/sharedfs:ro -p 8080:8080 flagmansupport/imgproxy:latest
          
      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' 

      - name: Install dependencies
        run: |
          python -m pip install -q --upgrade pip
          python -m pip install -q -r requirements.txt -r requirements_dev.txt

      - name: Run tests
        run: |
          pytest   
